### PR TITLE
Reimplement zbs_flasher using click

### PR DESCRIPTION
**Pull request by hurator**
Restructured the zbs_flasher.py to make it more maintainable

* use Exceptions to separate control flow from actual data
* split cli commands and the actual ZBS Flasher interface
* in cases where path are joined, the proper python function is used
* made everything follow pep-8

there are still some places where we could use struct instead of bit-shifting values together,
but that would have no or negative impact on readability

### CODE REVIEW

**Comment by atc1441** [comment]
Hey, thank you for the work implementing it.

Unsure if i should merge it right now, 
the way click is implemented is very different to how the code was, need to get into the "@" declaration. 
Its a code style i personally not like that much as it is less raw and you dont see what happens behind the hood.

Also it seems something is broken as the flasher does not error out when flashing or reading if no ZBS243 is connected.

**Comment by hurator** [comment]
Thank you for your feedback,
I can understand that decorators might be hard to get a grasp on.
And I won't be offended if you don't want to merge this :)

as for the broken read if no device is connected:
I forgot to check the return value of CMD_ZBS_BEGIN, fixed in f994e214217010d12afafead313039e6c3dddad8

I've also now enabled command chaining.
So, flashing from stock now looks like:
`python zbs_flasher.py mac write custom-firmware/demo_firmware_2.9_33_V1.9.0.0.bin`

or to enable passthrough mode after flashing:
`python zbs_flasher.py write custom-firmware/demo_firmware_2.9_33_V1.9.0.0.bin monitor`

**Comment by atc1441** [comment]
Looks good, 
Would merge it now i like it :)

One thing that may be better for new users, an error will now end up in a full traceback. A short and understandable error message would be good. No need to implement it yourself just an idea for the future.

Screenshot_20230219-133243_TeamViewer

**Comment by atc1441** [comment]
Just recheck the current version and i even implemented an error message there, so something like this.

Unbenannt

**Comment by hurator** [comment]
okay, will do.

Just to verify what was happening: did you remove the Tag during flashing?

**Comment by atc1441** [comment]
Yes, i tested a few different things like not having a tag inserted or as in that error message removing mid flash or just wiggeling it a bit to trigger a faulty connection

**Comment by hurator** [comment]
how important is the reset after flashing?

Would it be okay, only to reset after writing to flash?
For example: I think esp-idf resets the target when entering monitor/pass-through mode, and it's not very useful if you just want to know whats going on without restarting.

The error now looks like this:
```
Welcome to the ZBS-Flasher Utility
No Serial port given, trying to guess...
Using port /dev/ttyUSB0
Writing MAC address '00-00-02-1b-6c-35-3b-1d' to infopage
Reading into mac_backups/0000021b6c353b1d.bin  [####################################]  100%
All done!
Erasing infopage... Done.
Writing mac_backups/0000021b6c353b1d.bin to Infopage  [####################################]  100%
All done!
Erasing flash... Done.
Writing custom-firmware/demo_firmware_2.9_33_V1.9.0.0.bin to Flash  [####################----------------]   57%  00:00:03
Error: Writing to flash failed at 0x04a38 tried to write 250 bytes: Writing command returned an error
```

**Comment by atc1441** [comment]
A reset is just needed at the end of each interaction.

But of course menadorty to get any firmware running again. For example even if you just dump the flash it is nice to have the firmware running again after that


The log looks good

**Pull request merged**
